version: '3.5'
services:
#  trade-app-1:
#    build: .
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: rootroot
#      POSTGRES_DB: parser_db
#      POSTGRES_HOST: postgres
#      DB_PORT: 5432
#      JAVA_PORT: 8084
#      KEYCLOAK_HOST: keycloak
#      KEYCLOAK_PORT: 8080
#      KEYCLOAK_PROXY: keycloak
#    ports:
#      - "8084:8084"
#      - "5005:5005"
#    depends_on:
#      - postgres
#      - keycloak


  keycloak:
    depends_on:
      - postgres
    image: mihaibob/keycloak:18.0.2-legacy
    container_name: keycloak
    ports:
      - 9990:9990
      - 8080:8080
    volumes:
      - ./keycloak:/opt/jboss/keycloak/imports
    environment:
      - 'KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/realm.json -Dkeycloak.profile.feature.upload_scripts=enabled'
      - 'KEYCLOAK_USER=admin'
      - 'KEYCLOAK_PASSWORD=admin'
      - 'DB_VENDOR=POSTGRES'
      - 'DB_ADDR=postgres'
      - 'DB_DATABASE=keycloak'
      - 'DB_USER=postgres'
      - 'DB_PASSWORD=rootroot'
      - 'KEYCLOAK_FEATURES=scripts'
      - 'KC_HTTP_PORT=8080'

  postgres:
    image: 'postgres:10'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=rootroot'
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
